name: Erlang Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: Erlang benchmarks using Erlang OTP 29.0.0

services:
  erlang-container:
    image: erlang:29.0.0
    command: sleep infinity

flow:
  - name: Erlang-Fasta
    container: erlang-container
    commands:
      - type: console
        command: erlc /tmp/repo/benchmarks/erlang/fasta/fasta.erl
      - type: console
        command: erl -pa /tmp/repo/benchmarks/erlang/fasta -noshell -smp enable -run fasta main 100
