name: Dart Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: Dart benchmarks using Dart SDK 3.9.4

services:
  dart-container:
    image: dart:3.9.4-sdk
    command: sleep infinity

flow:
  - name: Dart-Binary-Trees
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/binary-trees/main.dart -o /tmp/main
      - type: console
        command: /tmp/main 21

  - name: Dart-Fannkuch-Redux
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/fannkuch-redux/main.dart -o /tmp/main
      - type: console
        command: /tmp/main 12

  - name: Dart-K-Nucleotide
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/k-nucleotide/main.dart -o /tmp/main
      - type: console
        command: sh -c "/tmp/main < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Dart-N-Body
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/n-body/main.dart -o /tmp/main
      - type: console
        command: /tmp/main 50000000

  - name: Dart-Regex-Redux
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/regex-redux/main.dart -o /tmp/main
      - type: console
        command: sh -c "/tmp/main < /tmp/repo/inputs/fasta-5000000.txt"

  - name: Dart-Spectral-Norm
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/spectral-norm/main.dart -o /tmp/main
      - type: console
        command: /tmp/main 5500
