name: Dart Benchmark (K-Nucleotide)
author: André Brandão <https://github.com/brandao07>
description: Dart benchmarks using Dart SDK 3.9.4

services:
  dart-container:
    image: dart:3.9.4-sdk
    command: sleep infinity

flow:
  - name: Dart-K-Nucleotide
    container: dart-container
    commands:
      - type: console
        command: dart compile exe /tmp/repo/benchmarks/dart/k-nucleotide/main.dart -o /tmp/main
      - type: console
        command: sh -c "/tmp/main < /tmp/repo/inputs/fasta-2500000.txt"


