name: Java Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: Java benchmarks using GraalVM Native Image 23.0.2

services:
  java-container:
    image: ghcr.io/graalvm/native-image-community:23.0.2
    entrypoint: /bin/sh
    command: -c "sleep infinity"

flow:
  - name: Java-Binary-Trees
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/binary-trees/build_in_tmp.sh
      - type: console
        command: /tmp/java-build/binary-trees/binarytrees.graalvmaot-7.graalvmaot_run 21

  - name: Java-Fannkuch-Redux
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/fannkuch-redux/build_in_tmp.sh
      - type: console
        command: /tmp/java-build/fannkuch-redux/fannkuchredux.graalvmaot_run 12

  - name: Java-K-Nucleotide
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/k-nucleotide/build_in_tmp.sh
      - type: console
        command: sh -c "/tmp/java-build/k-nucleotide/knucleotide.graalvmaot_run 0 < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Java-N-Body
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/n-body/build_in_tmp.sh
      - type: console
        command: /tmp/java-build/n-body/nbody.graalvmaot-4.graalvmaot_run 50000000

  - name: Java-Regex-Redux
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/regex-redux/build_in_tmp.sh
      - type: console
        command: sh -c "/tmp/java-build/regex-redux/regexredux.graalvmaot-3.graalvmaot_run 0 < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Java-Spectral-Norm
    container: java-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/java/spectral-norm/build_in_tmp.sh
      - type: console
        command: /tmp/java-build/spectral-norm/spectralnorm.graalvmaot-3.graalvmaot_run 5500
