name: Rust Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: Rust benchmarks using Rust 1.93 Alpine

services:
  rust-container:
    image: rust:1.93-alpine
    command: sleep infinity

flow:
  - name: Rust-Binary-Trees
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/binary-trees/build_in_tmp.sh
      - type: console
        command: /tmp/cargo-target/binary-trees/release/binary-trees 21

  - name: Rust-Fannkuch-Redux
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/fannkuch-redux/build_in_tmp.sh
      - type: console
        command: /tmp/cargo-target/fannkuch-redux/release/fannkuch-redux 12

  - name: Rust-K-Nucleotide
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/k-nucleotide/build_in_tmp.sh
      - type: console
        command: sh -c "/tmp/rust-k-nucleotide < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Rust-N-Body
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/n-body/build_in_tmp.sh
      - type: console
        command: /tmp/rust-n-body 50000000

  - name: Rust-Regex-Redux
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/regex-redux/build_in_tmp.sh
      - type: console
        command: sh -c "/tmp/rust-regex-redux < /tmp/repo/inputs/fasta-5000000.txt"

  - name: Rust-Spectral-Norm
    container: rust-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/rust/spectral-norm/build_in_tmp.sh
      - type: console
        command: /tmp/rust-spectral-norm 5500
