name: CPP Benchmark (Fannkuch-Redux)
author: André Brandão <https://github.com/brandao07>
description: CPP benchmarks using GCC 15.2.0

services:
  cpp-container:
    image: gcc:15.2.0
    setup-commands:
      - shell: bash
        command: apt-get update && apt-get install -y --fix-missing libboost-dev && rm -rf /var/lib/apt/lists/*
    command: sleep infinity

flow:
  - name: CPP-Fannkuch-Redux
    container: cpp-container
    commands:
      - type: console
        command: g++ -pipe -O3 -fomit-frame-pointer -march=native /tmp/repo/benchmarks/cpp/fannkuch-redux/main.cpp -o /tmp/main
      - type: console
        command: /tmp/main 12


