name: CPP Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: CPP benchmarks using GCC 15.2.0

services:
  cpp-container:
    image: gcc:15.2.0
    setup-commands:
      - shell: bash
        command: apt-get update && apt-get install -y --fix-missing libboost-dev && rm -rf /var/lib/apt/lists/*
      - command: g++ -pipe -O3 -fomit-frame-pointer -march=native -std=c++20 /tmp/repo/benchmarks/cpp/fasta/main.cpp -o /tmp/main
    command: sleep infinity

flow:
  - name: CPP-Fasta
    container: cpp-container
    commands:
      - type: console
        command: /tmp/main 25000000
