name: Ruby Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: Ruby benchmarks using Ruby 3.4 with YJIT

services:
  ruby-container:
    image: ruby:3.4
    command: sleep infinity

flow:
  # - name: Ruby-Binary-Trees
  #   container: ruby-container
  #   commands:
  #     - type: console
  #       command: sh /tmp/repo/benchmarks/ruby/binary-trees/build_in_tmp.sh
  #     - type: console
  #       command: /tmp/ruby-binary-trees 21

  # - name: Ruby-Fannkuch-Redux
  #   container: ruby-container
  #   commands:
  #     - type: console
  #       command: sh /tmp/repo/benchmarks/ruby/fannkuch-redux/build_in_tmp.sh
  #     - type: console
  #       command: /tmp/ruby-fannkuch-redux 12

  # - name: Ruby-K-Nucleotide
  #   container: ruby-container
  #   commands:
  #     - type: console
  #       command: sh /tmp/repo/benchmarks/ruby/k-nucleotide/build_in_tmp.sh
  #     - type: console
  #       command: sh -c "/tmp/ruby-k-nucleotide < /tmp/repo/inputs/fasta-2500000.txt"

  # - name: Ruby-N-Body
  #   container: ruby-container
  #   commands:
  #     - type: console
  #       command: sh /tmp/repo/benchmarks/ruby/n-body/build_in_tmp.sh
  #     - type: console
  #       command: /tmp/ruby-n-body 50000000

  # - name: Ruby-Spectral-Norm
  #   container: ruby-container
  #   commands:
  #     - type: console
  #       command: sh /tmp/repo/benchmarks/ruby/spectral-norm/build_in_tmp.sh
  #     - type: console
  #       command: /tmp/ruby-spectral-norm 5500

  - name: Ruby-Regex-Redux
    container: ruby-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/ruby/regex-redux/build_in_tmp.sh
      - type: console
        command: sh -c "/tmp/ruby-regex-redux < /tmp/repo/inputs/fasta-5000000.txt"
