name: Ruby Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: Ruby benchmarks using Ruby 3.4 with YJIT

services:
  ruby-container:
    image: ruby:3.4
    command: sleep infinity

flow:
  - name: Ruby-Fasta
    container: ruby-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/ruby/fasta/build_in_tmp.sh
      - type: console
        command: /tmp/ruby-fasta 100
