name: Ruby Benchmark (Regex-Redux)
author: André Brandão <https://github.com/brandao07>
description: Ruby benchmarks using Ruby 3.4 with YJIT

services:
  ruby-container:
    image: ruby:3.4
    setup-commands:
      - command: sh /tmp/repo/benchmarks/ruby/regex-redux/build_in_tmp.sh
    command: sleep infinity

flow:
  - name: Ruby-Regex-Redux
    container: ruby-container
    commands:
      - type: console
        shell: sh
        command: /tmp/ruby-regex-redux < /tmp/repo/inputs/fasta-100.txt

