name: Swift Benchmark (Fannkuch-Redux)
author: André Brandão <https://github.com/brandao07>
description: Swift benchmarks using Swift 6.0.3 (runs on container architecture, e.g. arm64 on Apple Silicon)

services:
  swift-container:
    image: swift:6.0.3
    setup-commands:
      - command: swiftc /tmp/repo/benchmarks/swift/fannkuch-redux/main.swift -Ounchecked -wmo -o /tmp/swift-fannkuch-redux
    command: sleep infinity

flow:
  - name: Swift-Fannkuch-Redux
    container: swift-container
    commands:
      - type: console
        command: /tmp/swift-fannkuch-redux 6


