name: Lua Benchmark (Binary-Trees)
author: André Brandão <https://github.com/brandao07>
description: Lua benchmarks using Lua 5.5 + LuaRocks Alpine 3.22

services:
  lua-container:
    image: nickblah/lua:5.5-luarocks-alpine3.22
    command: sleep infinity

flow:
  - name: Lua-Binary-Trees
    container: lua-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/lua/binary-trees/build_in_tmp.sh
      - type: console
        command: lua /tmp/lua-build/binary-trees/binarytrees.lua-4.lua_run 21


