name: FSharp Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: FSharp benchmarks using .NET SDK 9.0

services:
  fsharp-container:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    command: sleep infinity

flow:
  - name: FSharp-Fasta
    container: fsharp-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/fsharp/fasta/build_in_tmp.sh
      - type: console
        command: /tmp/fsharp-fasta 100
