name: PHP Benchmark (Fannkuch-Redux)
author: André Brandão <https://github.com/brandao07>
description: PHP benchmarks using PHP CLI

services:
  php-container:
    image: php:8.4-cli
    setup-commands:
      - shell: sh
        command: docker-php-ext-install -j"$(nproc)" shmop pcntl sysvmsg && docker-php-ext-enable shmop pcntl sysvmsg
    command: sleep infinity

flow:
  - name: PHP-Fannkuch-Redux
    container: php-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/php/fannkuch-redux/build_in_tmp.sh
      - type: console
        command: /tmp/php-fannkuch-redux 6


