name: PHP Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: PHP benchmarks using PHP CLI

services:
  php-container:
    image: php:8.4-cli
    setup-commands:
      - shell: sh
        command: docker-php-ext-install -j"$(nproc)" shmop pcntl && docker-php-ext-enable shmop pcntl
      - command: sh /tmp/repo/benchmarks/php/fasta/build_in_tmp.sh
    command: sleep infinity


flow:
  - name: PHP-Fasta
    container: php-container
    commands:
      - type: console
        command: /tmp/php-fasta 25000000
