name: PHP Benchmark (Spectral-Norm)
author: André Brandão <https://github.com/brandao07>
description: PHP benchmarks using PHP CLI

services:
  php-container:
    image: php:8.4-cli
    setup-commands:
      - shell: sh
        command: docker-php-ext-install -j"$(nproc)" shmop pcntl sysvmsg && docker-php-ext-enable shmop pcntl sysvmsg
      - command: sh /tmp/repo/benchmarks/php/spectral-norm/build_in_tmp.sh
    command: sleep infinity

flow:
  - name: PHP-Spectral-Norm
    container: php-container
    commands:
      - type: console
        command: /tmp/php-spectral-norm 500


