name: CSharp Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: CSharp benchmarks using .NET SDK 9.0

services:
  csharp-container:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    command: sleep infinity

flow:
  - name: CSharp-Binary-Trees
    container: csharp-container
    commands:
      - type: console
        command: bash -c "dotnet new console -n app --output /tmp/out --force && cp /tmp/repo/benchmarks/csharp/binary-trees/main.cs /tmp/out/Program.cs && cd /tmp/out && dotnet run -c Release -- 21"

  - name: CSharp-Fannkuch-Redux
    container: csharp-container
    commands:
      - type: console
        command: bash -c "dotnet new console -n app --output /tmp/out --force && cp /tmp/repo/benchmarks/csharp/fannkuch-redux/main.cs /tmp/out/Program.cs && cd /tmp/out && dotnet run -c Release -p:AllowUnsafeBlocks=true -- 12"

  - name: CSharp-K-Nucleotide
    container: csharp-container
    commands:
      - type: console
        command: bash -c "dotnet new console -n app --output /tmp/out --force && cp /tmp/repo/benchmarks/csharp/k-nucleotide/main.cs /tmp/out/Program.cs && cd /tmp/out && dotnet run -c Release -p:AllowUnsafeBlocks=true -- 0 < /tmp/repo/inputs/fasta-2500000.txt"

  # - name: CSharp-N-Body
  #   container: csharp-container
  #   commands:
  #     - type: console
  #       command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native /tmp/repo/benchmarks/c/n-body/main.c -o /tmp/main
  #     - type: console
  #       command: /tmp/main 50000000

  # - name: CSharp-Regex-Redux
  #   container: csharp-container
  #   commands:
  #     - type: console
  #       command: bash -c "dotnet new console -n app --output /tmp/out --force && cp /tmp/repo/benchmarks/csharp/regex-redux/main.cs /tmp/out/Program.cs && cd /tmp/out && dotnet run -c Release -p:AllowUnsafeBlocks=true -- 0 < /tmp/repo/inputs/fasta-2500000.txt"

  - name: CSharp-Spectral-Norm
    container: csharp-container
    commands:
      - type: console
        command: bash -c "dotnet new console -n app --output /tmp/out --force && cp /tmp/repo/benchmarks/csharp/spectral-norm/main.cs /tmp/out/Program.cs && cd /tmp/out && dotnet run -c Release -p:AllowUnsafeBlocks=true -- 12"
