name: CSharp Benchmark (K-Nucleotide)
author: André Brandão <https://github.com/brandao07>
description: CSharp benchmarks using .NET SDK 9.0

services:
  csharp-container:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    setup-commands:
      - command: sh /tmp/repo/benchmarks/csharp/setup_dependencies.sh
    command: sleep infinity

flow:
  - name: CSharp-K-Nucleotide
    container: csharp-container
    commands:
      - type: console
        command: sh /tmp/repo/benchmarks/csharp/k-nucleotide/build_in_tmp.sh
      - type: console
        shell: sh
        command: /tmp/csharp-k-nucleotide 0 < /tmp/repo/inputs/fasta-2500000.txt
