name: CSharp Benchmark (N-Body)
author: André Brandão <https://github.com/brandao07>
description: CSharp benchmarks using .NET SDK 9.0

services:
  csharp-container:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    setup-commands:
      - command: sh /tmp/repo/benchmarks/csharp/setup_dependencies.sh
      - command: sh /tmp/repo/benchmarks/csharp/n-body/build_in_tmp.sh
    command: sleep infinity

flow:
  - name: CSharp-N-Body
    container: csharp-container
    commands:
      - type: console
        command: /tmp/csharp-n-body 500
