name: Go Benchmark (N-Body)
author: André Brandão <https://github.com/brandao07>
description: Go benchmarks using Golang 1.25 Alpine

services:
  go-container:
    image: golang:1.25-alpine
    command: sleep infinity

flow:
  - name: Go-N-Body
    container: go-container
    commands:
      - type: console
        command: sh -c "go build -o /tmp/go-n-body /tmp/repo/benchmarks/go/n-body/main.go"
      - type: console
        command: /tmp/go-n-body 50000000


