name: Haskell Benchmark (Binary-Trees)
author: André Brandão <https://github.com/brandao07>
description: Haskell benchmarks using GHC 9.10.1

services:
  haskell-container:
    image: haskell:9.10.1
    setup-commands:
      - shell: bash
        command: cabal update && cabal install --lib parallel ghc-compact
      - shell: sh
        command: mkdir -p /tmp/haskell-binary-trees && ghc -O2 -XBangPatterns -threaded -rtsopts -XMagicHash /tmp/repo/benchmarks/haskell/binary-trees/main.hs -outputdir /tmp/haskell-binary-trees -odir /tmp/haskell-binary-trees -hidir /tmp/haskell-binary-trees -o /tmp/haskell-binary-trees/main
    command: sleep infinity

flow:
  - name: Haskell-Binary-Trees
    container: haskell-container
    commands:
      - type: console
        command: /tmp/haskell-binary-trees/main +RTS -N4 -K128M -H -RTS 21
