name: Haskell Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: Haskell benchmarks using GHC 9.10.1

services:
  haskell-container:
    image: haskell:9.10.1
    setup-commands:
      - shell: bash
        command: cabal update && cabal install --lib massiv
    command: sleep infinity

flow:
  - name: Haskell-Fasta
    container: haskell-container
    commands:
      - type: console
        shell: sh
        command: mkdir -p /tmp/haskell-fasta && ghc -O2 -XBangPatterns -threaded -rtsopts -XMagicHash  /tmp/repo/benchmarks/haskell/fasta/main.hs -outputdir /tmp/haskell-fasta -odir /tmp/haskell-fasta -hidir /tmp/haskell-fasta -o /tmp/haskell-fasta/main
      - type: console
        command: /tmp/haskell-fasta/main +RTS -N4 -RTS 100
