name: Haskell Benchmark (K-Nucleotide)
author: André Brandão <https://github.com/brandao07>
description: Haskell benchmarks using GHC 9.10.1

services:
  haskell-container:
    image: haskell:9.10.1
    setup-commands:
      - shell: bash
        command: cabal update && cabal install --lib parallel hashable hashtables containers bytestring
      - shell: sh
        command: mkdir -p /tmp/haskell-k-nucleotide && ghc -O2 -XBangPatterns -threaded -rtsopts -XMagicHash /tmp/repo/benchmarks/haskell/k-nucleotide/main.hs -outputdir /tmp/haskell-k-nucleotide -odir /tmp/haskell-k-nucleotide -hidir /tmp/haskell-k-nucleotide -o /tmp/haskell-k-nucleotide/main
    command: sleep infinity

flow:
  - name: Haskell-K-Nucleotide
    container: haskell-container
    commands:
      - type: console
        shell: sh
        command: /tmp/haskell-k-nucleotide/main +RTS -N4 -K2048M -RTS 0 < /tmp/repo/inputs/fasta-2500000.txt
