name: Python Benchmark (Fannkuch-Redux)
author: André Brandão <https://github.com/brandao07>
description: Python benchmarks using Python 3.14 Alpine

services:
  python-container:
    image: python:3.14.0-alpine3.22
    command: sleep infinity

flow:
  - name: Python-Fannkuch-Redux
    container: python-container
    commands:
      - type: console
        command: python3 -OO /tmp/repo/benchmarks/python/fannkuch-redux/main.py 6


