name: NodeJS Benchmark (Spectral-Norm)
author: André Brandão <https://github.com/brandao07>
description: NodeJS benchmarks using Node 25 Alpine

services:
  node-container:
    image: node:25-alpine3.21
    command: sleep infinity

flow:
  - name: NodeJS-Spectral-Norm
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/spectral-norm/main.js 500

